-- LINK FOR INSTALLING DEBUG ADAPTERS
-- https://codeberg.org/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#dart
return {
	-- 	"mfussenegger/nvim-dap",
	-- 	lazy = true,
	-- 	ft = "dart",
	-- 	dependencies = {
	-- 		"theHamsta/nvim-dap-virtual-text",
	-- 		"rcarriga/nvim-dap-ui",
	-- 		"nvim-neotest/nvim-nio",
	-- 	},
	-- 	config = function()
	-- 		local dap = require("dap")
	-- 		local dapui = require("dapui")
	-- 		dap.listeners.before.attach.dapui_config = function()
	-- 			dapui.open()
	-- 		end
	-- 		dap.listeners.before.launch.dapui_config = function()
	-- 			dapui.open()
	-- 		end
	-- 		dap.listeners.before.event_terminated.dapui_config = function()
	-- 			dapui.close()
	-- 		end
	-- 		dap.listeners.before.event_exited.dapui_config = function()
	-- 			dapui.close()
	-- 		end
	-- 		vim.keymap.set("n", "<leader>dc", function()
	-- 			dap.continue()
	-- 		end)
	-- 		vim.keymap.set("n", "<F10>", function()
	-- 			dap.step_over()
	-- 		end)
	-- 		vim.keymap.set("n", "<F11>", function()
	-- 			dap.step_into()
	-- 		end)
	-- 		vim.keymap.set("n", "<F12>", function()
	-- 			dap.step_out()
	-- 		end)
	-- 		vim.keymap.set("n", "<leader>b", function()
	-- 			dap.toggle_breakpoint()
	-- 		end)
	-- 		vim.keymap.set("n", "<leader>B", function()
	-- 			dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
	-- 		end)
	-- 		vim.keymap.set("n", "<leader>lp", function()
	-- 			dap.set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
	-- 		end)
	-- 		vim.keymap.set("n", "<leader>dr", function()
	-- 			dap.repl.open()
	-- 		end)
	-- 		vim.keymap.set("n", "<leader>dl", function()
	-- 			dap.run_last()
	-- 		end)
	--
	-- 		-- DART DEBUGGING CONFIG
	-- 		dap.adapters.dart = {
	-- 			type = "executable",
	-- 			command = vim.fn.stdpath("data") .. "/mason/bin/dart-debug-adapter",
	-- 			args = { "dart" },
	-- 		}
	-- 		dap.adapters.flutter = {
	-- 			type = "executable",
	-- 			command = vim.fn.stdpath("data") .. "/mason/bin/dart-debug-adapter",
	-- 			args = { "flutter" },
	-- 		}
	-- 		dap.configurations.dart = {
	-- 			{
	-- 				type = "dart",
	-- 				request = "launch",
	-- 				name = "Launch dart",
	-- 				dartSdkPath = "/home/h3ad5h0t/development/flutter/bin/cache/dart-sdk",
	-- 				flutterSdkPath = "/home/h3ad5h0t/development/flutter",
	-- 				program = "${workspaceFolder}/lib/main.dart",
	-- 				cwd = "${workspaceFolder}",
	-- 			},
	-- 			{
	-- 				type = "flutter",
	-- 				request = "launch",
	-- 				name = "Launch flutter",
	-- 				dartSdkPath = "/home/h3ad5h0t/development/flutter/bin/cache/dart-sdk",
	-- 				flutterSdkPath = "/home/h3ad5h0t/development/flutter",
	-- 				program = "${workspaceFolder}/lib/main.dart",
	-- 				cwd = "${workspaceFolder}",
	-- 			},
	-- 		}
	-- 	end,
}
